<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">ReadFile</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCnRyeSB7
DQpTdHJpbmcgZmlsZVBhdGggPSAiL29wdC9zb2Z0d2FyZWFnL2NvbW1vbi9ydW50aW1lL2J1bmRs
ZXMvbnVtL2VjbGlwc2UvYXJ0aWZhY3RzLnhtbCI7IC8vIEhhcmRjb2RlZCBmaWxlIHBhdGgNCmlm
IChmaWxlUGF0aCAhPSBudWxsICYmICFmaWxlUGF0aC5pc0VtcHR5KCkpIHsNCnRyeSB7DQpTeXN0
ZW0ub3V0LnByaW50bG4oIkF0dGVtcHRpbmcgdG8gcmVhZCBmaWxlOiAiICsgZmlsZVBhdGgpOw0K
U3RyaW5nIGZpbGVDb250ZW50ID0gcmVhZEZpbGUoZmlsZVBhdGgpOw0KU3lzdGVtLm91dC5wcmlu
dGxuKCJGaWxlIGNvbnRlbnQ6Iik7DQpTeXN0ZW0ub3V0LnByaW50bG4oZmlsZUNvbnRlbnQpOw0K
SURhdGFVdGlsLnB1dChwaXBlbGluZUN1cnNvciwgImZpbGVDb250ZW50IiwgZmlsZUNvbnRlbnQp
Ow0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KU3lzdGVtLmVyci5wcmludGxuKCJFcnJvciBy
ZWFkaW5nIGZpbGU6ICIgKyBlLmdldE1lc3NhZ2UoKSk7DQplLnByaW50U3RhY2tUcmFjZSgpOyAv
LyBQcmludCBzdGFjayB0cmFjZSBmb3IgZGV0YWlsZWQgZXJyb3IgaW5mbw0KdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24obnVsbCwgIkVycm9yIHJlYWRpbmcgZmlsZTogIiArIGUuZ2V0TWVzc2Fn
ZSgpLCBmaWxlUGF0aCwgZSwgbnVsbCk7DQp9DQp9IGVsc2Ugew0KU3lzdGVtLmVyci5wcmludGxu
KCJGaWxlIHBhdGggaXMgZW1wdHkgb3IgbnVsbC4iKTsNCnRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKCJGaWxlIHBhdGggaXMgZW1wdHkgb3IgbnVsbC4iKTsNCn0NCn0gZmluYWxseSB7DQpwaXBl
bGluZUN1cnNvci5kZXN0cm95KCk7DQp9DQp9DQoNCnB1YmxpYyBzdGF0aWMgU3RyaW5nIHJlYWRG
aWxlKFN0cmluZyBmaWxlUGF0aCkgdGhyb3dzIElPRXhjZXB0aW9uIHsNClN0cmluZ0J1aWxkZXIg
Y29udGVudCA9IG5ldyBTdHJpbmdCdWlsZGVyKCk7DQpGaWxlIGZpbGUgPSBuZXcgRmlsZShmaWxl
UGF0aCk7DQoNCmlmICghZmlsZS5leGlzdHMoKSkgew0KdGhyb3cgbmV3IElPRXhjZXB0aW9uKCJG
aWxlIG5vdCBmb3VuZCBhdCBwYXRoOiAiICsgZmlsZVBhdGgpOw0KfQ0KDQp0cnkgKEJ1ZmZlcmVk
UmVhZGVyIHJlYWRlciA9IG5ldyBCdWZmZXJlZFJlYWRlcihuZXcgRmlsZVJlYWRlcihmaWxlKSkp
IHsNClN0cmluZyBsaW5lOw0Kd2hpbGUgKChsaW5lID0gcmVhZGVyLnJlYWRMaW5lKCkpICE9IG51
bGwpIHsNCmNvbnRlbnQuYXBwZW5kKGxpbmUpLmFwcGVuZCgiXG4iKTsNCn0NCn0NCg0KcmV0dXJu
IGNvbnRlbnQudG9TdHJpbmcoKTs=</value>
</Values>
